name = "onions-without-tears"
compatibility_date = "2026-01-30"
main = "src/worker.ts"

routes = [
  { pattern = "onionswithouttears.co.uk", custom_domain = true },
  { pattern = "www.onionswithouttears.co.uk", custom_domain = true }
]

[[kv_namespaces]]
binding = "VISITORS"
id = "8d30806bf5cb4a2fa92bfd1b439c4ec1"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"
