name = "onions-without-tears"
compatibility_date = "2026-01-30"
main = "src/worker.ts"

[[kv_namespaces]]
binding = "VISITORS"
id = "REPLACE_WITH_KV_NAMESPACE_ID"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "404-page"
